### ISSUE TITLE
I found some more broken stuff

### ISSUE THREAD

**Issue by binarynoise** [vednoc/custom-fonts#11]
## links in code + some other nested elements in code blocks:
```
https://github.com/vednoc/custom-fonts/issues/11
```
![grafik](https://user-images.githubusercontent.com/50302352/208548774-313f048b-df3e-410c-aaec-4940536565b4.png)
-> would it make sense to exclude the complete subtree to the code/pre-blocks?

## **bold** text appears normal to me: 
![grafik](https://user-images.githubusercontent.com/50302352/208548427-0f350579-ce02-42b9-b058-6acd507559ac.png)

**Comment by vednoc** [comment]
Could you [reinstall the userstyle](https://raw.githubusercontent.com/vednoc/custom-fonts/main/fonts.user.styl) to test my fix for the first part? I presume you're using an extension since GitHub doesn't seem to have this functionality natively.

As for the second part, I suppose we could have checkboxes to exclude font style/weight from default HTML elements. Alternatively, we could override styles for said HTML elements by giving users more options. If you have an idea how to go about it, please let me know.

P.S. I suppose mono fonts could be improved as well. Perhaps this needs its own issue.

**Comment by binarynoise** [comment]
I updated the userstyle as you said, and yes, it helped. Automatic update must have stopped since I edited it manually...
I do use an extension: Refined Github. And yes, that's the "culprit" which adds that stuff. I forgot about that.

Again it's my own fault.
I set the font weight to 400 for everything because e.g. Soundcloud would display with the hair variant otherwise.
But maybe overriding font weight for bold elements and headings would help to preserve that formatting

**Comment by vednoc** [comment]
Awesome! If you made changes manually then yes, as Stylus does have that mechanism. If you didn't, Stylus won't update a userstyle until its `@version` field is incremented.

I don't see how it's your fault. Anyways, I'll add two new options to override font weight of headings and bold elements, as well as one new option to override italic elements. That should cover everything, if I'm not mistaken.

**Comment by binarynoise** [comment]
That would be great. Thank you!

**Comment by binarynoise** [comment]
I reinstalled the script again and the link in the code block is monospace again :+1:

**Comment by vednoc** [comment]
Closing this issue as it was fixed in https://github.com/vednoc/custom-fonts/commit/6e1df1eaee2be55d9a6d14a59df95412288c9543.
