### ISSUE TITLE
twitch broken

### ISSUE THREAD

**Issue by binarynoise** [vednoc/custom-fonts#18]
`append(icons, '[aria-hidden=true]')` causes the whole site to be interpreted as icon and thus excluded from applying the font when hovering over a channel and the channel description pops up.

It's probably because after the update, I also include all children of items in the selectors. Would it make sense not to do that with icons?

**Comment by vednoc** [comment]
Oddly enough, it works on my end. Perhaps we could use `append(icons, 'i[aria-hidden=true]', 'svg[aria-hidden=true]')` to be much more specific since that ARIA attribute is often used for more than just icons.

Yeah! It would make more sense to have it like before rewrite, where we intentionally included all children in places where we knew they would be necessary. That should result in a less buggy behavior, too.
